---
# Launch and do not wait for result, connection will drop
- name: Kubernetes | Create HNS network
  win_shell: |
    New-HnsNetwork -Name {{ sdn_info.sdn_network_name }} -AddressPrefix {{OVN_SUBNET}} -Gateway {{OVN_GATEWAY_IP}} -Type Transparent -AdapterName "{{ interface_name }}"
  async: 10
  poll: 0

# Wait for docker to create the HNS Network and the new adapter. Connection will
# drop shortly when doing this, wait for the connection to come back
- name: Kubernetes | Wait for system to become reachable over WinRM
  wait_for_connection:
    # The connection should come back usually after a few seconds
    delay: 5
    timeout: 60
