---
- name: Kubelet | Delete kubeconfig
  win_file:
    path: "{{ install_info.install_path }}/kubeconfig.yaml"
    state: absent
- name: Kubelet | Create kubeconfig
  win_lineinfile:
    path: "{{ install_info.install_path }}/kubeconfig.yaml"
    create: yes
    line: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: local
        cluster:
          server: http://{{ kubernetes_info.MASTER_IP }}:8080
      users:
      - name: kubelet
      contexts:
      - context:
          cluster: local
          user: kubelet
        name: kubelet-context
      current-context: kubelet-context
    newline: unix

- set_fact:
    pod_infra_container_image: "{{kubernetes_info.infracontainername_1709}}"
  when: ansible_kernel == "10.0.16299.0"

- set_fact:
    pod_infra_container_image: "apprenda/pause"
  when: ansible_kernel == "10.0.14393.0"

- name: Setting environment variable for windows 2016
  win_environment:
    state: present
    name: "CONTAINER_NETWORK"
    value: "{{ docker_info.docker_network_name }}"
    level: machine
  when: ansible_kernel == "10.0.14393.0"

- name: Kubelet | Create Kubelet service
  win_service:
    name: kubelet
    path: '"{{ install_info.install_path }}\\servicewrapper.exe" kubelet "{{ install_info.install_path }}\\kubelet.exe" --hostname-override="{{ ansible_hostname }}" --cluster-dns="{{ kubernetes_info.K8S_DNS_SERVICE_IP }}" --cluster-domain="{{ kubernetes_info.K8S_DNS_DOMAIN }}" --pod-infra-container-image="{{pod_infra_container_image}}" --resolv-conf="" --kubeconfig="{{ install_info.install_path }}\\kubeconfig.yaml" --network-plugin=cni --cni-bin-dir="{{ install_info.install_path }}\\cni" --cni-conf-dir="{{ install_info.install_path }}\\cni" --log-dir="{{ install_info.install_path }}"'
    display_name: Kubernetes Kubelet
    description: Kubernetes Kubelet service
    username: LocalSystem
    password: ""

- name: Kubelet | Set kubectl context
  win_shell: |
    {{ install_info.install_path }}\\kubectl.exe config set-cluster default-cluster --server={{ kubernetes_info.MASTER_IP }}:8080
    {{ install_info.install_path }}\\kubectl.exe config set-context local --cluster=default-cluster --user=default-admin
    {{ install_info.install_path }}\\kubectl.exe config use-context local

# Start the kubelet to ensure OVN gives subnet to this minion
- name: Kubelet | Start service kubelet
  win_service:
    name: kubelet
    state: started

- name: Kubelet | Wait 15 seconds for kubelet to register this node
  pause:
    seconds: 15
