---
- name: Docker | Download latest docker
  win_shell: |
    Find-PackageProvider -Name "Nuget" | Install-PackageProvider -Force
    Install-Module -Name "DockerMsftProvider" -Repository "PSGallery" -Force
    Install-Package -Name "Docker" -ProviderName "DockerMsftProvider" -Force -RequiredVersion "{{ docker_version }}"

- name: Docker | Start docker service
  win_service:
    name: docker
    state: started
